sprint 10
Jiv4ii/java-filmorate pull request #5
Opened 2023-09-21 13:47 UTC by Jiv4ii

2023-09-22 08:11 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые требуется исправить!

Желаю удачи!

2023-09-22 08:11 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.getFilm(filmId).getLikes().add(userId);
Не стоит это модифицировать в сервисе, опять же это деталь хранилища. 
У тебя хранилище может быть не в ОЗУ, а на диске (в файле или СУБД), поэтому добавление лайков - должен быть метод хранилища, который в себя инкапсулирует логику

2023-09-22 08:11 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void deleteLike(Long filmId, Long userId) {
Аналогично тому, что писал выше

2023-09-22 08:11 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
Замечания аналогичные `FilmService`

2023-09-22 08:11 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final FilmStorage filmStorage;
Напрямую в хранилище из контроллера не ходим!
Это противоречит смыслу слоеной архитектуры!

2023-09-22 12:55 UTC, Jiv4ii commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getPopularFilms(@RequestParam(name = "count", defaultValue = "10") Integer count) {
Если параметров несколько, name обязателен, без него не будет работать

2023-09-23 08:54 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Осталось некоторое количество замечаний, которые надо исправить!

Желаю удачи!

2023-09-23 08:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getPopularFilms(@RequestParam(name = "count", defaultValue = "10") Integer count) {
Ты имеешь в виду, если есть параметр `defaultValue`?

Вот, как пример, тут все работает без `name` с параметром `defaultValue`, или я неправильно понял твою мысль?
https://www.baeldung.com/spring-request-param#a-default-value-for-the-request-parameter

2023-09-23 08:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (count < 0) {
Здесь наверное меньше либо равно нуля.
Странно, если у тебя просят 0 записей

2023-09-23 08:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.addLike(userId, friendId);
Метод наверное `addFriend` должен называться :)

2023-09-23 08:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.removeLike(userId, friendId);
`removeFriend`

2023-09-23 08:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUser(userId) == null) {
Да, когда данные хранятся в ОЗУ, мы не сильно переживаем за количество запросов, так как получение этих данных работает очень быстро, но существуют разные способы хранения данных и лучше дважды за одними и теми же данными не ходить в хранилище

```java
User user = userStorage.getUser(userId);
if (user == null) {
    // some code
}
return user.getFriends();
```

2023-09-23 08:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (filmMap.get(id) == null) {
А почему где-то `containsKey`, а где-то `get`?

2023-09-23 08:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    long getId();
Этот метод стоит убрать из интерфейса

2023-09-23 10:09 UTC, Jiv4ii commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getPopularFilms(@RequestParam(name = "count", defaultValue = "10") Integer count) {
Упустил этот момент

2023-09-24 17:32 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-09-25 12:07 UTC, merged