Sprint 11.0
Jiv4ii/java-filmorate pull request #7
Opened 2023-10-01 20:54 UTC by Jiv4ii

2023-10-03 06:54 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторые замечания, которые надо исправить!

Желаю удачи!

2023-10-03 06:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreConroller.java
> +    @GetMapping()
Здесь не нужны скобки

2023-10-03 06:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaConroller.java
> +    @GetMapping()
Не нужны скобки

2023-10-03 06:54 UTC, LexLippi commented on src/main/resources/schema.sql
> +drop table if exists film_genres cascade;
По возможности стоит избегать таких `drop`-ов, так как представь, кто будет пользоваться приложением, в котором при каждом обновлении удаляются все пользовательские данные?
Это не очень приятно

2023-10-03 06:54 UTC, LexLippi commented on src/main/resources/schema.sql
> +
1. Если поле не может быть `null`, то его необходимо помечать, как `not null`
2. У типа `varchar` стоит указывать разумные или общепринятые ограничения сверху. Например, длина адреса электронной почты по RFC не может превышать 255 символов
https://www.rfc-editor.org/errata/eid1690
3. Если поле в таблице уникально, то необходимо помечать его, как `unique`

2023-10-03 06:54 UTC, LexLippi commented on src/main/resources/schema.sql
> +insert into genres (genre)
Здесь и ниже можно воспользоваться оператором `merge`:
https://en.wikipedia.org/wiki/Merge_(SQL)

2023-10-03 06:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/implementation/inmemory/InMemoryUserStorage.java
> +package ru.yandex.practicum.filmorate.storage.implementation.inmemory;
Хранилища в памяти необходимо удалить, чтобы в дальнейшем не мучаться с их поддержкой

2023-10-03 06:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/implementation/inmemory/InMemoryFilmStorage.java
> +/*
Уже писал

2023-10-03 06:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/implementation/db/userstorage/UserDbStorage.java
> +        return new HashSet<>(jdbcTemplate.query("select * from users where id in (select friend_id from user_friends where user_id = ?)", ps -> ps.setLong(1, id), userRowMapper));
Можно используя `join` обойтись без подзапросов

2023-10-03 06:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/implementation/db/userstorage/UserDbStorage.java
> +        return new HashSet<>(jdbcTemplate.query("select * from users where id in (select f1.friend_id from user_friends f1 INNER JOIN user_friends f2 on f1.friend_id = f2.friend_id where f1.user_id =
Можно обойтись без подзапросов

2023-10-03 06:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/implementation/db/userstorage/UserDbStorage.java
> +    private long id = 1;
Это зачем?
`JdbcTemplate` умеет сам генерировать идентификаторы

2023-10-03 06:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/implementation/db/filmstorage/FilmDbStorage.java
> +    }
В таком случае мы не знаем кто конкретно ставил лайк фильму, соответственно один человек может заспамить фильм лайками, что будет очень плохо.
Ну и мы не сможем отображать пользователей, которые ставили лайк фильму даже для них самих, что довольно печально, скорее всего, стоит добавить таблицу `film_likes`

2023-10-03 14:18 UTC, Jiv4ii commented on src/main/java/ru/yandex/practicum/filmorate/storage/implementation/db/userstorage/UserDbStorage.java
> +        return new HashSet<>(jdbcTemplate.query("select * from users where id in (select f1.friend_id from user_friends f1 INNER JOIN user_friends f2 on f1.friend_id = f2.friend_id where f1.user_id =
Поломалась голова, не смог обойтись

2023-10-03 16:51 UTC, Jiv4ii commented
Github выдает ошибку сборки в  файле FilmDbTest, что идет ссылка внешнего ключа на несуществующую строку, у меня все проходит на компьютере и всё до чего додумался не помогло выявить конкретную причину ошибки. От перегруза голова уже не особо соображает, а в четверг жесткий дедлайн, что добавляет еще и стресса, прошу помочь с этой ошибкой или хотя бы намекнуть на причину.

2023-10-04 08:05 UTC, LexLippi commented
Привет!

Вообще по вопросам тестов лучше обращаться к наставнику, а не ко мне, но сообщение об ошибке похоже на то, что работа других тестов выполняет на выполнение твоего. Вообще в `JUnit` не гарантируется порядок выполнения тестов, поэтому на серверах Github и на твоей локальной машине он может отличаться. 

Чтобы избежать этой проблемы во всех тестах, который взаимодействуют с СУБД советую использовать аннотацию `@Transactional`:

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Transactional.html

Если это не поможет, то попробуй связаться со своим наставником и уточнить у него этот вопрос

2023-10-04 12:02 UTC, Jiv4ii commented
Помогло использование @DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)

2023-10-05 06:58 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2023-10-09 22:37 UTC, merged